# Generated by Django 6.1 on 2026-09-13 11:14

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('institution', models.CharField(max_length=100)),
                ('faculty_or_major', models.CharField(max_length=100)),
                ('degree', models.CharField(max_length=100)),
                ('started_at', models.DateField()),
                ('ended_at', models.DateField(blank=True, null=True)),
                ('description', models.TextField(blank=True, default='')),
            ],
        ),
    ]
