# Generated by Django 6.1 on 2026-09-20 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_project'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='experience',
            name='thumbnail',
        ),
    ]
